---
- name: Debian | Dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2 
      - software-properties-common
    state: present
    update_cache: true
    
- name: Debian | Add docker key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
 
- name: Debian | Add docker repo
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

- name: Debian | Add Kubernetes apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Debian | Add Kubernetes repository.
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    update_cache: true

- name: Debian | Install packages
  apt:
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - kubeadm
      - kubelet
      - kubectl
    update_cache: yes
