---
- name: Init k8s cluster
  shell: kubeadm init --apiserver-advertise-address="192.168.56.10" --apiserver-cert-extra-sans="192.168.56.10"  --node-name node1 --pod-network-cidr=192.168.0.0/16

- name: Commands for start using k8s
  shell: "{{item}}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Generation of k8s join command
  shell: kubeadm token create --print-join-command 2> /dev/null
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
  become: false

- name: Install flannel pod network
  become: false
  command: kubectl apply -f {{ kubernetes_flannel_file }}
